pyrpl:
  background_color: ''
  dock_positions: "\0\0\0\xFF\0\0\0\0\xFD\0\0\0\x01\0\0\0\x02\0\0\0\0\0\0\0\0\xFC\x01\
    \0\0\0\x01\xFC\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\0\0\xFF\xFF\xFF\xFA\xFF\xFF\xFF\xFF\
    \x01\0\0\0\v\xFB\0\0\02\0a\0s\0g\0s\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0d\0o\0\
    k\0u\0m\0e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0\
    0\0i\0q\0s\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0d\0o\0k\0u\0m\0e\0n\0t\0)\0\0\0\
    \0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\02\0p\0i\0d\0s\0 \0(\0N\0\
    e\0u\0e\0s\0 \0T\0e\0x\0t\0d\0o\0k\0u\0m\0e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\
    \0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\06\0s\0c\0o\0p\0e\0s\0 \0(\0N\0e\0u\0e\0s\0 \0\
    T\0e\0x\0t\0d\0o\0k\0u\0m\0e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\
    \xFF\xFF\xFB\0\0\02\0i\0i\0r\0s\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0d\0o\0k\0\
    u\0m\0e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\04\0\
    t\0r\0i\0g\0s\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0d\0o\0k\0u\0m\0e\0n\0t\0)\0\
    \0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0H\0n\0e\0t\0w\0o\0r\0\
    k\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0d\0o\0k\0u\0m\0\
    e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0J\0s\0p\0\
    e\0c\0t\0r\0u\0m\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0\
    d\0o\0k\0u\0m\0e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\
    \0\0\0@\0c\0u\0r\0v\0e\0v\0i\0e\0w\0e\0r\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0\
    d\0o\0k\0u\0m\0e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\
    \0\0\0@\0p\0y\0r\0p\0l\0c\0o\0n\0f\0i\0g\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0\
    d\0o\0k\0u\0m\0e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\
    \0\0\08\0l\0o\0c\0k\0b\0o\0x\0 \0(\0N\0e\0u\0e\0s\0 \0T\0e\0x\0t\0d\0o\0k\0u\0\
    m\0e\0n\0t\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\0\0\x03 \0\0\x02\
    /\0\0\0\x04\0\0\0\x04\0\0\0\b\0\0\0\b\xFC\0\0\0\0"
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: Neues Textdokument
  window_position:
  - 0
  - 0
  - 800
  - 600
redpitaya:
  autostart: true
  delay: 0.05
  frequency_correction: 1.0
  hostname: 131.246.145.83
  leds_off: true
  monitor_server_name: monitor_server
  password: root
  port: 2222
  reloadfpga: true
  reloadserver: false
  serverbinfilename: fpga.bin
  serverdirname: //opt//pyrpl//
  silence_env: false
  sshport: 22
  timeout: 1
  user: root
scope:
  curve_name: scope curve
networkanalyzer:
  curve_name: networkanalyzer curve
spectrumanalyzer:
  curve_name: spectrumanalyzer curve
lockbox:
  sequence:
  - outputs: {}
