pyrpl:
  background_color: ''
  dock_positions: "\0\0\0\xFF\0\0\0\0\xFD\0\0\0\x01\0\0\0\x02\0\0\x05\xF1\0\0\x03\xC1\
    \xFC\x01\0\0\0\x01\xFC\0\0\0\0\0\0\x05\xF1\0\0\0y\0\xFF\xFF\xFF\xFC\x02\0\0\0\x02\
    \xFB\0\0\0&\0s\0c\0o\0p\0e\0s\0 \0(\0t\0e\0s\0t\01\09\00\05\00\08\0)\x01\0\0\0\
    \x15\0\0\x01\xE8\0\0\0P\0\xFF\xFF\xFF\xFC\0\0\x02\x01\0\0\x01\xD5\0\0\0e\x01\0\
    \0\x14\xFA\0\0\0\0\x01\0\0\0\v\xFB\0\0\0(\0l\0o\0c\0k\0b\0o\0x\0 \0(\0t\0e\0s\0\
    t\01\09\00\05\00\08\0)\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0]\0\xFF\xFF\xFF\xFB\0\0\
    \0\"\0a\0s\0g\0s\0 \0(\0t\0e\0s\0t\01\09\00\05\00\08\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\
    \0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0 \0i\0q\0s\0 \0(\0t\0e\0s\0t\01\09\00\05\00\0\
    8\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0\"\0p\0i\0d\0\
    s\0 \0(\0t\0e\0s\0t\01\09\00\05\00\08\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\
    \xFF\xFF\xFF\xFB\0\0\0\"\0i\0i\0r\0s\0 \0(\0t\0e\0s\0t\01\09\00\05\00\08\0)\0\0\
    \0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0$\0t\0r\0i\0g\0s\0 \0\
    (\0t\0e\0s\0t\01\09\00\05\00\08\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\
    \xFF\xFB\0\0\08\0n\0e\0t\0w\0o\0r\0k\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0t\0e\0s\0\
    t\01\09\00\05\00\08\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\
    \0\0:\0s\0p\0e\0c\0t\0r\0u\0m\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0t\0e\0s\0t\01\09\0\
    0\05\00\08\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\00\0c\0\
    u\0r\0v\0e\0v\0i\0e\0w\0e\0r\0 \0(\0t\0e\0s\0t\01\09\00\05\00\08\0)\x01\0\0\0\0\
    \xFF\xFF\xFF\xFF\0\0\0]\0\xFF\xFF\xFF\xFB\0\0\00\0p\0y\0r\0p\0l\0c\0o\0n\0f\0\
    i\0g\0 \0(\0t\0e\0s\0t\01\09\00\05\00\08\0)\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\
    ]\0\xFF\xFF\xFF\xFB\0\0\0(\0l\0o\0c\0k\0b\0o\0x\0 \0(\0t\0e\0s\0t\01\09\00\05\0\
    0\08\0)\x02\0\0\a\xE5\0\0\0\\\0\0\x06-\0\0\x03f\0\0\x05\xF1\0\0\0\0\0\0\0\x04\0\
    \0\0\x04\0\0\0\b\0\0\0\b\xFC\0\0\0\0"
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: test190508
  window_position:
  - 1503
  - 125
  - 1521
  - 1002
redpitaya:
  autostart: true
  defaultport: 2222
  delay: 0.05
  frequency_correction: 1.0
  hostname: 131.246.145.66
  leds_off: true
  monitor_server_name: monitor_server
  password: root
  port: 2222
  reloadfpga: true
  reloadserver: false
  serverbinfilename: fpga.bin
  serverdirname: //opt//pyrpl//
  silence_env: false
  sshport: 22
  timeout: 1
  user: root
scope:
  curve_name: scope curve
  duration: 2.147483648
  input1: in1
  input2: in2
  rolling_mode: true
  running_state: running_continuous
  trigger_source: ch2_positive_edge
  average: false
  ch2_active: true
  trace_average: 1
  xy_mode: false
  trigger_delay: 0.0
  hysteresis: 0.0
  ch1_active: true
  threshold: 0.199951171875
networkanalyzer:
  curve_name: networkanalyzer curve
spectrumanalyzer:
  curve_name: spectrumanalyzer curve
  running_state: paused
  display_input1_baseband: true
  input1_baseband: in1
lockbox:
  sequence:
  - duration: 0.2
    function_call: ''
    gain_factor: 873.0
    input: port1
    outputs:
      output1:
        lock_on: false
        offset: 0.0
        reset_offset: false
      output2:
        lock_on: true
        offset: 0.2
        reset_offset: true
      piezo:
        lock_on: true
        offset: 0.25
        reset_offset: true
    setpoint: 0.264
  outputs:
    output1:
      assisted_design: true
      i: 100.0
      p: 0.0
    output2:
      assisted_design: true
      dc_gain: 2.3887e-09
      i: 100.0
      max_voltage: 0.8
      min_voltage: -0.8
      output_channel: out2
      p: 0.0
    piezo:
      additional_filter:
      - 18.972756741396708
      - 37.94553157665012
      - 2428.6599415484384
      - 656885.0955548416
      analog_filter_cutoff: 1.3265288463352614
      assisted_design: false
      calibration_data:
        _analog_offset: 0.0
        _asg_phase: 0.0
        max: 0.0
        mean: 0.0
        min: 0.0
        rms: 0.0
      d: 0.0
      dc_gain: 873.0
      desired_unity_gain_frequency: 0.0046
      extra_module: None
      extra_module_state: None
      i: 0.0046
      max_voltage: 0.8
      min_voltage: -0.8
      output_channel: out2
      p: 0.003467696923974328
      sweep_amplitude: 0.30577974319458
      sweep_frequency: 0.06830048561096191
      sweep_offset: 0.0
      sweep_waveform: ramp
      tf_curve: 0
      tf_type: filter
      unit: V/V
  classname: AG_Lockbox
  inputs:
    pdh1:
      calibration_data:
        max: 0.0
        mean: 0.0
        min: 0.0
        rms: 0.0
      input_signal: in2
      mod_amp: 0.0
      mod_freq: 0.0
      mod_output: out2
      quadrature_factor: 0.0
    port1:
      calibration_data:
        max: 0.4495849609375
        mean: 0.26962779462337494
        min: 0.089111328125
        rms: 0.12496902670969813
      input_signal: in2
    port2:
      calibration_data:
        max: 0.4498291015625
        mean: 0.2703084275126457
        min: 0.0888671875
        rms: 0.1249178952588018
      input_signal: in2
  final_stage:
    duration: 0.0
    function_call: ''
    gain_factor: 873.0
    input: port1
    outputs:
      piezo:
        lock_on: true
        offset: 0.25
        reset_offset: true
    setpoint: 0.264
  wavelength: 6.33e-07
  is_locked_threshold: 0.08
scope_states:
  autosweep:
    average: true
    ch1_active: true
    ch2_active: true
    curve_name: scope curve
    duration: 8.589934592
    hysteresis: 0.0
    input1: in2
    input2: out2
    rolling_mode: false
    running_state: stopped
    threshold: 0.199951171875
    trace_average: 1
    trigger_delay: 0.0
    trigger_source: asg1
    xy_mode: false
lockbox_states: {}
inputs_states: {}
piezo_states: {}
pid2: {}
pid2_states: {}
asg0:
  waveform: dc
pyrplconfig: {}
scopes: {}
networkanalyzer_states: {}
pyrplconfig_states: {}
spectrumanalyzer_states: {}
curveviewer: {}
iir:
  data_curve: -1
  input: in2
  inputfilter: 0
  loops: 5
  'on': true
  output_direct: 'off'
  poles: []
  zeros: []
iq0:
  acbandwidth: 0
  amplitude: 0.0019989013671875
  bandwidth:
  - 0
  - 0
  frequency: 0.0
  gain: 0.0
  input: in2
  output_direct: 'off'
  quadrature_factor: 1.0
