pyrpl:
  background_color: ''
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: test_19_05_03
  dock_positions: "\0\0\0\xFF\0\0\0\0\xFD\0\0\0\x01\0\0\0\x02\0\0\a\x80\0\0\x03\xF9\
    \xFC\x01\0\0\0\x01\xFC\0\0\0\0\0\0\a\x80\0\0\0y\0\xFF\xFF\xFF\xFA\0\0\0\n\x01\0\
    \0\0\f\xFB\0\0\0,\0s\0c\0o\0p\0e\0s\0 \0(\0t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\0\
    3\0)\x03\0\0\x03\x8E\0\0\0r\0\0\x03\x11\0\0\x01W\xFB\0\0\0(\0p\0i\0d\0s\0 \0(\0\
    t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\03\0)\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0]\0\xFF\
    \xFF\xFF\xFB\0\0\0(\0a\0s\0g\0s\0 \0(\0t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\03\0\
    )\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0]\0\xFF\xFF\xFF\xFB\0\0\0&\0i\0q\0s\0 \0(\0\
    t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\03\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\
    \xFF\xFF\xFF\xFB\0\0\0(\0i\0i\0r\0s\0 \0(\0t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\0\
    3\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0*\0t\0r\0i\0g\0\
    s\0 \0(\0t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\03\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\
    \0\x16\0\xFF\xFF\xFF\xFB\0\0\0>\0n\0e\0t\0w\0o\0r\0k\0a\0n\0a\0l\0y\0z\0e\0r\0\
    \ \0(\0t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\03\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\
    \x16\0\xFF\xFF\xFF\xFB\0\0\0@\0s\0p\0e\0c\0t\0r\0u\0m\0a\0n\0a\0l\0y\0z\0e\0r\0\
    \ \0(\0t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\03\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\
    \x16\0\xFF\xFF\xFF\xFB\0\0\06\0c\0u\0r\0v\0e\0v\0i\0e\0w\0e\0r\0 \0(\0t\0e\0s\0\
    t\0_\01\09\0_\00\05\0_\00\03\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\
    \xFB\0\0\06\0p\0y\0r\0p\0l\0c\0o\0n\0f\0i\0g\0 \0(\0t\0e\0s\0t\0_\01\09\0_\00\0\
    5\0_\00\03\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0.\0l\0\
    o\0c\0k\0b\0o\0x\0 \0(\0t\0e\0s\0t\0_\01\09\0_\00\05\0_\00\03\0)\x01\0\0\0\0\xFF\
    \xFF\xFF\xFF\0\0\0]\0\xFF\xFF\xFF\xFB\0\0\0.\0l\0o\0c\0k\0b\0o\0x\0 \0(\0t\0e\0\
    s\0t\0_\01\09\0_\00\05\0_\00\03\0)\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\0\0\0\0\0\
    \0\0\a\x80\0\0\0\0\0\0\0\x04\0\0\0\x04\0\0\0\b\0\0\0\b\xFC\0\0\0\0"
  window_position:
  - 1912
  - -8
  - 1920
  - 1058
redpitaya:
  autostart: true
  delay: 0.05
  frequency_correction: 1.0
  hostname: 131.246.145.91
  leds_off: true
  monitor_server_name: monitor_server
  password: root
  port: 2222
  reloadfpga: true
  reloadserver: false
  serverbinfilename: fpga.bin
  serverdirname: //opt//pyrpl//
  silence_env: false
  sshport: 22
  timeout: 1
  user: root
scope:
  average: false
  ch1_active: true
  ch2_active: true
  curve_name: scope curve
  duration: 0.536870912
  input1: out2
  input2: in2
  rolling_mode: false
  running_state: running_continuous
  trigger_delay: 0.0
  trigger_source: immediately
  hysteresis: 0.0
  threshold: 0.0
networkanalyzer:
  curve_name: networkanalyzer curve
spectrumanalyzer:
  curve_name: spectrumanalyzer curve
lockbox:
  classname: Interferometer
  final_stage:
    duration: 0.0
    function_call: ''
    gain_factor: 1.0
    input: port2
    outputs:
      piezo:
        lock_on: true
        offset: 0.0
        reset_offset: true
    setpoint: 0.0
  inputs:
    port1:
      calibration_data:
        max: 0.063720703125
        mean: 0.0052027031779289246
        min: -0.0625
        rms: 0.04328391882914252
      input_signal: lockbox.outputs.piezo
    port2:
      calibration_data:
        max: 0.6932373046875
        mean: 0.4062809720635414
        min: 0.131591796875
        rms: 0.19765616750733314
      input_signal: in2
  is_locked_threshold: 5.0
  outputs:
    output1:
      assisted_design: true
      i: 100.0
      p: 0.0
    output2:
      assisted_design: true
      i: 100.0
      p: 0.0
    piezo:
      additional_filter:
      - 18.972756741396708
      - 0
      - 0
      - 1.1857967662444893
      analog_filter_cutoff: 0.0
      assisted_design: false
      dc_gain: 348150.0
      desired_unity_gain_frequency: 333
      extra_module: None
      i: 0.0
      output_channel: out2
      p: 0.0
      sweep_amplitude: 0.1
      sweep_frequency: 1.0
      tf_type: flat
      unit: nm/V
  sequence:
  - duration: 1.0
    gain_factor: 1.0
    outputs:
      piezo:
        lock_on: true
        reset_offset: true
    setpoint: 0.0
  wavelength: 6.33e-07
scopes: {}
scope_states:
  autosweep:
    average: false
    ch1_active: true
    ch2_active: true
    curve_name: scope curve
    duration: 0.536870912
    hysteresis: 0.0
    input1: out2
    input2: in2
    rolling_mode: false
    running_state: running_continuous
    threshold: 0.0
    trace_average: 1
    trigger_delay: 0.0
    trigger_source: immediately
    xy_mode: false
asg0:
  amplitude: 0.0999755859375
  cycles_per_burst: 0
  frequency: 0.5820766091346741
  offset: 0.0
  output_direct: 'off'
  trigger_source: immediately
  waveform: ramp
pid0:
  input: in2
  output_direct: 'off'
  setpoint: 0.5
  p: 0.000244140625
  i: 0.0
  inputfilter:
  - 0
  - -4.743187489051999
  - 0
  - 0
  max_voltage: 0.9998779296875
  min_voltage: -1.0
pid1:
  i: 0.0
  input: in2
  output_direct: 'off'
  p: 0.0
  setpoint: 0.5
iir:
  loops: 5
  'on': true
