pyrpl:
  background_color: ''
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: test19_05_07_03
redpitaya:
  hostname: 131.246.145.91
