pyrpl:
  background_color: ''
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: test19_04_30_01
redpitaya:
  serverbinfilename: fpga.bin
