pyrpl:
  background_color: ''
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: test19_04_29
redpitaya:
  hostname: 131.246.145.95
